image:
  file: .gitpod.Dockerfile

tasks:
  - name: Nats
    init: |
      cp .env.sample .env
      gp sync-done env-file
    command: |
      docker-compose up -d
  - name: PWA
    init: |
      cd app/
      pnpm install
      gp sync-await env-file
    command: |
      sed -i "s,VITE_NATS_URL=.*,VITE_NATS_URL=wss://4223-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}," ../.env
      pnpm start
  - name: Go setup
    init: |
      go mod tidy

vscode:
  extensions:
    - editorconfig.editorconfig
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - Vue.volar
    - voorjaar.windicss-intellisense
    - golang.go

ports:
  - port: 4222
    onOpen: notify
  - port: 4223
    onOpen: notify
  - port: 8222
    onOpen: notify
  - port: 3000
    onOpen: open-browser
