version: "2"
linters:
  default: none
  enable:
    - bidichk
    - errcheck
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
    - whitespace
  settings:
    misspell:
      locale: US
    revive:
      enable-default-rules: true
      rules:
        - name: var-naming
          exclude: [""]
          arguments:
            - [] # AllowList
            - [] # DenyList
            - - skip-package-name-checks: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
