package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"fmt"

	"github.com/kiel-live/kiel-live/hub/graph/model"
)

// Map is the resolver for the map field.
func (r *subscriptionResolver) Map(ctx context.Context, north float64, east float64, south float64, west float64) (<-chan *model.Map, error) {
	panic(fmt.Errorf("not implemented: Map - map"))
}

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
