// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LocationInput struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
	Heading   int     `json:"heading"`
}

type Mutation struct {
}

type Query struct {
}

type RouteInput struct {
	ID       string            `json:"id"`
	Provider string            `json:"provider"`
	Name     string            `json:"name"`
	Type     string            `json:"type"`
	IsActive bool              `json:"isActive"`
	Stops    []*RouteStopInput `json:"stops"`
}

type RouteStopInput struct {
	ID       string         `json:"id"`
	Location *LocationInput `json:"location"`
}

type StopArrivalInput struct {
	Name      string `json:"name"`
	VehicleID string `json:"vehicleId"`
	TripID    string `json:"tripId"`
	RouteID   string `json:"routeId"`
	RouteName string `json:"routeName"`
	Direction string `json:"direction"`
	State     string `json:"state"`
	Planned   string `json:"planned"`
	Eta       int    `json:"eta"`
	Platform  string `json:"platform"`
}

type StopInput struct {
	ID       string              `json:"id"`
	Provider string              `json:"provider"`
	Name     string              `json:"name"`
	Type     string              `json:"type"`
	Location *LocationInput      `json:"location"`
	Routes   []string            `json:"routes,omitempty"`
	Alerts   []string            `json:"alerts,omitempty"`
	Arrivals []*StopArrivalInput `json:"arrivals,omitempty"`
	Vehicles []*VehicleInput     `json:"vehicles,omitempty"`
}

type Subscription struct {
}

type TripArrivalInput struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	State   string `json:"state"`
	Planned string `json:"planned"`
}

type TripInput struct {
	ID        string              `json:"id"`
	Provider  string              `json:"provider"`
	VehicleID string              `json:"vehicleId"`
	Direction string              `json:"direction"`
	Arrivals  []*TripArrivalInput `json:"arrivals"`
	Path      []*LocationInput    `json:"path"`
}

type VehicleInput struct {
	ID       string         `json:"id"`
	Provider string         `json:"provider"`
	Name     string         `json:"name"`
	Type     string         `json:"type"`
	State    string         `json:"state"`
	Battery  string         `json:"battery"`
	Location *LocationInput `json:"location"`
	TripID   string         `json:"tripId"`
}
