minimumReleaseAge: 1440 # 1 day

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild

strictPeerDependencies: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - rollup@2.80.0

trustPolicyIgnoreAfter: 262980 # 6 months
minimumReleaseAgeExclude:
  # Renovate security update: vite@7.3.2
  - vite@7.3.2
