default_platform(:android)

platform :android do
  desc 'Runs all the tests'
  lane :test do
    gradle(project_dir: 'android-app', task: 'test')
  end

  lane :build do
    gradle(project_dir: 'android-app', task: 'clean')
    gradle(project_dir: 'android-app', task: 'bundleRelease')
  end

  lane :build_and_sign do
    releaseFilePath = File.join(Dir.pwd, 'android-keys.jks')
    gradle(project_dir: 'android-app', task: 'clean')
    gradle(
      project_dir: 'android-app',
      task: 'bundle',
      build_type: 'Release',
      print_command: false,
      properties: {
        'android.injected.signing.store.file' => releaseFilePath,
        'android.injected.signing.store.password' => ENV['ANDROID_KEYSTORE_PASSWORD'],
        'android.injected.signing.key.alias' => 'key0',
        'android.injected.signing.key.password' => ENV['ANDROID_KEY_PASSWORD'],
      }
    )
  end

  desc 'Submit a new beta build to Google Play'
  lane :beta do
    build_and_sign
    upload_to_play_store(track: 'beta', release_status: 'draft')
  end

  desc 'Submit a new production build to Google Play'
  lane :production do
    build_and_sign
    upload_to_play_store(release_status: 'draft')
  end
end
