name: Check GO

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: {}

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: "go.mod"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          version: v2.12.2

  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: "go.mod"
      - name: Run unit tests
        env:
          TZ: "Europe/Berlin"
        run: |
          go test ./... -coverprofile=coverage.out -covermode=atomic
      - name: Comment PR with coverage
        uses: ./.github/actions/go-coverage-comment
        if: github.event_name == 'pull_request'
        with:
          coverage-file: coverage.out
          min-threshold: '70.0'
          github-token: ${{ secrets.GITHUB_TOKEN }}
