name: Check GO

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: {}

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version-file: "go.mod"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20
        with:
          version: v2.11.4

  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version-file: "go.mod"
      - name: Run unit tests
        env:
          TZ: "Europe/Berlin"
        run: |
          go test ./... -coverprofile=coverage.out -covermode=atomic
      - name: Comment PR with coverage
        uses: ./.github/actions/go-coverage-comment
        if: github.event_name == 'pull_request'
        with:
          coverage-file: coverage.out
          min-threshold: '70.0'
          github-token: ${{ secrets.GITHUB_TOKEN }}
