name: Check JS

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320
        with:
          package_json_file: app/package.json

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: app/package.json
          cache: "pnpm"
          cache-dependency-path: app

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: app

      - name: Typecheck
        run: pnpm run typecheck
        working-directory: app

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320
        with:
          package_json_file: app/package.json

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: app/package.json
          cache: "pnpm"
          cache-dependency-path: app

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: app

      - name: Lint
        run: pnpm run lint
        working-directory: app

  check-format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320
        with:
          package_json_file: app/package.json

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: app/package.json
          cache: "pnpm"
          cache-dependency-path: app

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: app

      - name: Check format
        run: pnpm run formatcheck
        working-directory: app

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320
        with:
          package_json_file: app/package.json

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: app/package.json
          cache: "pnpm"
          cache-dependency-path: app

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: app

      - name: Test
        run: pnpm run test
        working-directory: app
