name: Container

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

permissions: {}

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}

jobs:
  build-collector-images:
    name: Build collector container image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        collector:
          - kvg
          - nextbike
          - donkey
          - gtfs
          - ais
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set version
        id: version
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "value=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "value=next-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          fi

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ matrix.collector }}-collector
          tags: |
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=next,enable={{is_default_branch}}

      - name: Login to registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: collectors/Containerfile
          build-args: |
            COLLECTOR_NAME=${{ matrix.collector }}
            VERSION=${{ steps.version.outputs.value }}
