name: Container

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

permissions:
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}

jobs:
  build-collector-images:
    name: Build collector container image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        collector:
          - kvg
          - nextbike
          - donkey
          - gtfs
          - ais
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set version
        id: version
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "value=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "value=next-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          fi

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ matrix.collector }}-collector
          tags: |
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=next,enable={{is_default_branch}}

      - name: Login to registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: collectors/Containerfile
          build-args: |
            COLLECTOR_NAME=${{ matrix.collector }}
            VERSION=${{ steps.version.outputs.value }}
